# Generated by Django 6.0.3 on 2026-03-07 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('job_type', models.CharField(choices=[('single', 'Single Video'), ('playlist', 'Playlist')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('mp4', 'MP4'), ('mp3', 'MP3'), ('webm', 'WebM')], default='mp4', max_length=10)),
                ('quality', models.CharField(choices=[('360p', '360p'), ('720p', '720p'), ('1080p', '1080p')], default='720p', max_length=10)),
                ('total_videos', models.IntegerField(blank=True, null=True)),
                ('downloaded_videos', models.IntegerField(default=0)),
                ('zip_file_path', models.FileField(blank=True, null=True, upload_to='zips/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='downloader.downloadjob')),
            ],
        ),
    ]
