# Generated by Django 6.0.3 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_downloadjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='selected_videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
